import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/containers/header/header.jsx';

/* ↓ Optimisation de police par NextJS */
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex min-h-screen flex-col items-center p-12">
          {children}
        </main>
      </body>
    </html>
  );
}
